// <auto-generated />
namespace ZumoCommunity.MeetupAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PartnerIsFeatured : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartnerIsFeatured));
        
        string IMigrationMetadata.Id
        {
            get { return "201702152016419_Partner-IsFeatured"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
