// <auto-generated />
namespace ZumoCommunity.MeetupAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TopicAssetAdjusted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopicAssetAdjusted));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131432099_TopicAsset-Adjusted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
